POST http://localhost:5100/api/add-post
content-type: application/json

{
  "imagesNumber": 3,
  "shoeModel": "SB Dunk High Pro",
  "shoeColor": "Mineral Slate Suede",
  "retailPrice": "549",
  "resellPrice": "700 - 800",
  "dateTime": {
    "day": 10,
    "month": 5,
    "year": 2022,
    "time": "10:00"
  },
  "dropType": "LEO",
  "app": "Nike SNKRS"
}